package nyc.charlton.roku


sealed class Info {
    data object None : Info()

    data class DeviceInfo(
        val udn: String?,
        val serialNumber: String?,
        val deviceId: String?,
        val advertisingId: String?,
        val vendorName: String?,
        val modelName: String?,
        val modelNumber: String?,
        val modelRegion: String?,
        val isTv: Boolean,
        val isStick: Boolean,
        val screenSize: Int,
        val panelId: Int,
        val mobileHasLiveTv: Boolean,
        val uiResolution: String?,
        val tunerType: String?,
        val supportsEthernet: Boolean,
        val wifiMac: String?,
        val wifiDriver: String?,
        val hasWifi5GSupport: Boolean,
        val ethernetMac: String?,
        val networkType: String?,
        val networkName: String?,
        val friendlyDeviceName: String?,
        val friendlyModelName: String?,
        val defaultDeviceName: String?,
        val userDeviceName: String?,
        val userDeviceLocation: String?,
        val buildNumber: String?,
        val softwareVersion: String?,
        val softwareBuild: Int,
        val lightningBaseBuildNumber: String?,
        val uiBuildNumber: String?,
        val uiSoftwareVersion: String?,
        val uiSoftwareBuild: Int,
        val secureDevice: Boolean,
        val language: String?,
        val country: String?,
        val locale: String?,
        val timeZoneAuto: Boolean,
        val timeZone: String?,
        val timeZoneName: String?,
        val timeZoneTz: String?,
        val timeZoneOffset: Int,
        val clockFormat: String?,
        val uptime: Int,
        val powerMode: String?,
        val supportsSuspend: Boolean,
        val supportsFindRemote: Boolean,
        val supportsAudioGuide: Boolean,
        val supportsRva: Boolean,
        val hasHandsFreeVoiceRemote: Boolean,
        val developerEnabled: Boolean,
        val searchEnabled: Boolean,
        val searchChannelsEnabled: Boolean,
        val voiceSearchEnabled: Boolean,
        val supportsPrivateListening: Boolean,
        val supportsPrivateListeningDtv: Boolean,
        val supportsWarmStandby: Boolean,
        val headphonesConnected: Boolean,
        val supportsAudioSettings: Boolean,
        val expertPqEnabled: String?,
        val supportsEcsTextedit: Boolean,
        val supportsEcsMicrophone: Boolean,
        val supportsWakeOnWlan: Boolean,
        val supportsAirplay: Boolean,
        val hasPlayOnRoku: Boolean,
        val hasMobileScreenSaver: Boolean,
        val supportUrl: String?,
        val grandCentralVersion: String?,
        val supportsTrc: String?,
        val trcVersion: String?,
        val trcChannelVersion: String?,
        val avSyncCalibrationEnabled: String?
    ): Info()
}